config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "static_pages#top"
  resources :users, only: %i[new create]
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  get "select_language", to: "conversions#select_language"
  get "conversions_hiragana_lao_hiragana_to_lao", to: "conversions/hiragana_lao#hiragana_to_lao"
  post "conversions_hiragana_lao_hiragana_to_lao", to: "conversions/hiragana_lao#hiragana_to_lao"
  get "conversions/hiragana_lao/hiragana_to_lao_result", to: "conversions/hiragana_lao#hiragana_to_lao_result", as: "hiragana_to_lao_result"
end

app/views/shared/_before_login_header.html.erb
<div class="header">
  <span class="header_logo">
    <%= link_to image_tag("S__22192130.jpg", height: "90"), root_path %>
  </span>
  <span class="header_right">
    <%= link_to 'ログイン', login_path, :class => 'header_button' %>
    <%= link_to '新規登録', new_user_path, :class => 'header_button' %>
  </span>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer_box">
    <span class="footer_button">利用規約</span>
    <span class="footer_button">プライバシーポリシー</span>
    <span class="footer_button">問い合わせ</span>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <span class="header_logo">
    <%= link_to image_tag("S__22192130.jpg", height: "90"), root_path %>
  </span>
  <span class="header_right">
    <%# <%= link_to 'ログアウト', logout_path, class: 'header_button', data: { turbo_method: :delete } %> %>
    <%= link_to '変換言語選択', select_language_path, :class => 'header_button' %>
  </span>
</div>